<?php
/**
 * Implements hook_cron().
 */
function custom_feature_cron_cron() {
  // Calculate the timestamp for seven days ago.
  $sevenDaysAgo = strtotime('-7 days');

  // Load news nodes that have the "feature" boolean field set to TRUE and are older than seven days.
  $query = \Drupal::entityQuery('node')
    ->condition('type', 'news')
    ->condition('status', 1) 
    ->condition('field_feature', 1) 
    ->condition('created', $sevenDaysAgo, '<'); 

  $nids = $query->execute();

  
  foreach ($nids as $nid) {
    $node = \Drupal\node\Entity\Node::load($nid);
    if ($node) {
      $node->set('field_feature', 0);
      $node->save();
    }
  }
}
